#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>

import sys
import click
import base64
from urllib import parse

sys.path.append(".")
import common.msg as cmsg


def decode_base64(s):
    b = s.encode("UTF-8")
    b = base64.b64decode(b)
    cmsg.from_to(s, b.decode('UTF-8'))


def decode_url(s):
    cmsg.from_to(s, parse.unquote(s))


@click.command()
@click.option("-b", "--base64", is_flag=True, help="Decode text with base64")
@click.option("-u",
              "--url",
              is_flag=True,
              help="Decode text with URL-decoding(percent-decoding) method")
@click.argument("args", nargs=-1)
@click.option("--debug", is_flag=True, help="debug mode")
def dcode(base64, url, args, debug):
    """
Decode text with base64/URL decoding algorithm.

Example:

\b
```
$ dc -b SGVsbG8gV29ybGQ=
`SGVsbG8gV29ybGQ=` => `Hello World`
```

\b
```
$ venv --base64 'SGVsbG8gV29ybGQ=' 'R29vZGJ5ZSBXb3JsZA=='
`SGVsbG8gV29ybGQ=` => `Hello World`
`R29vZGJ5ZSBXb3JsZA==` => `Goodbye World`
```
    """
    if len(args) == 0:
        cmsg.error(f"arguments is missing")
        exit(1)
    if base64:
        for a in args:
            decode_base64(a)
    elif url:
        for a in args:
            decode_url(a)
    else:
        cmsg.unknown_option()


if __name__ == "__main__":
    dcode()
