#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>

import sys
import click
import base64
from urllib import parse

sys.path.append(".")
import common.msg as cmsg


def output(src, dst):
    cmsg.echo(f"`{src}` => `{dst}`")


def encode_base64(s):
    b = s.encode("UTF-8")
    b = base64.b64encode(b)
    output(s, b.decode('UTF-8'))


def encode_url(s):
    output(s, parse.quote(s))


@click.command()
@click.option("-b", "--base64", is_flag=True, help="Encode text with base64")
@click.option("-u",
              "--url",
              is_flag=True,
              help="Encode text with URL-encoding(percent-encoding) method")
@click.argument("args", nargs=-1)
@click.option("--debug", is_flag=True, help="debug mode")
def vencode(base64, url, args, debug):
    """
Encode text with base64/URL encoding algorithm.

Example:

\b
```
$ venc -b Hello
$ Hello => SGVsbG8=
```

\b
```
$ venv --base64 'Hello World' 'Goodbye World'
$ Hello World => SGVsbG8gV29ybGQ=
$ Goodbye World => SGVsbG8gV29ybGQ=
```
    """
    if len(args) == 0:
        cmsg.error(f"arguments is missing")
        exit(1)
    if base64:
        for a in args:
            encode_base64(a)
    elif url:
        for a in args:
            encode_url(a)
    else:
        cmsg.unknown_option()


if __name__ == "__main__":
    vencode()
