#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>

import sys
import os
import click

sys.path.append(".")
import common.msg as cmsg


@click.command()
@click.option("-e",
              "--email",
              required=True,
              help="Email address to generate the SSH Key")
@click.option("--debug", is_flag=True, help="debug mode")
def vgenssh(email, debug):
    """
SSH Key Generator

It helps create `id_rsa` and `id_rsa.pub` with 4096 RSA method in your ~/.ssh directory using below commands:

\b
```
$ ssh-keygen -t rsa -b 4096 -C '{email}'
$ touch ~/.ssh/authorized_keys
$ chmod -R 700 ~/.ssh
$ chmod 600 ~/.ssh/authorized_keys
$ chmod 600 ~/.ssh/id_rsa
$ chmod 600 ~/.ssh/id_rsa.pub
```
"""
    if debug:
        cmsg.debug(f"email:{email}, debug:{debug}")
    os.system(f"ssh-keygen -t rsa -b 4096 -C '{email}'")
    os.system("touch ~/.ssh/authorized_keys")
    os.system("chmod -R 700 ~/.ssh")
    os.system("chmod 600 ~/.ssh/authorized_keys")
    os.system("chmod 600 ~/.ssh/id_rsa")
    os.system("chmod 600 ~/.ssh/id_rsa.pub")


if __name__ == '__main__':
    vgenssh()
